# This file was generated by GoReleaser. DO NOT EDIT.
cask "bwenv" do
  version "3.0.1"

  on_macos do
    on_arm do
      sha256 "91123ec6458da8e1f9a6972c13cbc4c23272a2dae577974b27848ca400747412"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f0fd50196a31580fed69a3d77a37307185e13896435f1b15dd11721552fe57e7"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "077aebd416ebba2cc4178eea128446f78a207cc5924ab6ba99e076697af30149"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "5ee24428d9114957954bc9a8b1b0b580a2ec3aef0efdd19ee768a11e215c688c"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-amd64.tar.gz"
    end
  end

  name "bwenv"
  desc "Sync secrets from password managers (Bitwarden, 1Password) into your shell with native, direnv or mise hooks"
  homepage "https://github.com/s1ks1/bwenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bwenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bwenv"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Install a provider CLI (Bitwarden bw or 1Password op), then run:

      bwenv init

    Follow the shell setup steps printed by init.
    Native shell activation is the default; bwenv config selects direnv or mise.
    Existing projects keep their configured hook. See the v3 migration guide:
      https://github.com/s1ks1/bwenv/blob/v3.0.0/docs/migration.md
  EOS
end
