# This file was generated by GoReleaser. DO NOT EDIT.
cask "bwenv" do
  version "2.0.6"

  on_macos do
    on_intel do
      sha256 "7ec3135b81c535781c60f565f66c0891f4ea1f91b3cac98503b9ac508f5510dc"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "608630d102cca4aa88c82c5ea0de8bf2b5e29a47088fa1df13d939d07b148e5b"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f8639e8ea5ab632c88bcd23395127ca57654408296f30e22d45313e0a919131"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "24bbb92b774f767af16bd828b30e4dc1832d9ade73aeb3711e9408061e6ebab2"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-arm64.tar.gz"
    end
  end

  name "bwenv"
  desc "Sync secrets from password managers (Bitwarden, 1Password) into your shell via direnv"
  homepage "https://github.com/s1ks1/bwenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bwenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bwenv"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started, run:

      bwenv status

    Make sure direnv is hooked into your shell:
      bash: eval "$(direnv hook bash)"
      zsh:  eval "$(direnv hook zsh)"
      fish: direnv hook fish | source
  EOS
end
