# This file was generated by GoReleaser. DO NOT EDIT.
cask "bwenv" do
  version "2.0.6"

  on_macos do
    on_intel do
      sha256 "df5dbb8e8f8c5fde292f85cf078092b8b5edbec1ae2ead739b30c205643a34f0"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "c31377a8c0a9a1ee7dcbdd96fc521f3547a2a8cbff4a72ecafcc52f086646703"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5830ab2b3ba15fcfa12e38097b3f79f8a5c4a484ed616531a2fb81820a8da395"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "90675d362356e8cd4369b02812963e8b4a288e4ab7e5a3db5946dc509da09bad"
      url "https://github.com/s1ks1/bwenv/releases/download/v#{version}/bwenv-#{version}-linux-arm64.tar.gz"
    end
  end

  name "bwenv"
  desc "Sync secrets from password managers (Bitwarden, 1Password) into your shell via direnv"
  homepage "https://github.com/s1ks1/bwenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bwenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bwenv"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To get started, run:

      bwenv status

    Make sure direnv is hooked into your shell:
      bash: eval "$(direnv hook bash)"
      zsh:  eval "$(direnv hook zsh)"
      fish: direnv hook fish | source
  EOS
end
